DO $$ BEGIN
  CREATE TYPE "FurnishedStatus" AS ENUM ('FURNISHED', 'SEMI_FURNISHED', 'UNFURNISHED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "ListingAvailability" AS ENUM ('AVAILABLE', 'RENTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "ListingPublicationStatus" AS ENUM ('PUBLISHED', 'UNPUBLISHED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "ListingMode" AS ENUM ('SHORT_TERM', 'LONG_TERM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "RentalDuration" ADD VALUE IF NOT EXISTS 'NIGHTLY';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'UNPUBLISHED';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'HOTEL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'GUEST_HOUSE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'FARMHOUSE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'OTHER';